# Generated by Django 4.0.3 on 2022-05-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('company_city', models.CharField(blank=True, max_length=50, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_contact', models.IntegerField(blank=True, null=True)),
                ('company_logo', models.FileField(blank=True, null=True, upload_to='company_logo/')),
                ('company_password', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fullname', models.CharField(blank=True, max_length=70, null=True)),
                ('user_age', models.IntegerField(blank=True, null=True)),
                ('user_education', models.CharField(blank=True, max_length=50, null=True)),
                ('user_experience', models.CharField(blank=True, max_length=50, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('user_contact', models.IntegerField(blank=True, null=True)),
                ('user_gender', models.CharField(blank=True, max_length=20, null=True)),
                ('user_city', models.CharField(blank=True, max_length=30, null=True)),
                ('user_photo', models.FileField(blank=True, null=True, upload_to='user_image/')),
                ('user_resume', models.FileField(blank=True, null=True, upload_to='user_resume/')),
                ('user_password', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
