# Generated by Django 4.0.3 on 2022-05-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_registration',
            name='company_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
