# Generated by Django 4.0.3 on 2022-05-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_company_registration_company_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_feedback_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user_feedback_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_feedback_profession', models.CharField(max_length=50, null=True)),
                ('user_feedback_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
