# Generated by Django 4.0.3 on 2022-05-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_employer_post_vacency'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_post_vacency',
            name='employer_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
