# Generated by Django 4.0.3 on 2022-05-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_employer_skill1_employer_post_vacency_employer_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer_post_vacency',
            name='employer_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employer_post_vacency',
            name='employer_enddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
