# Generated by Django 4.0.3 on 2022-05-05 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_employer_post_vacency_employer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidates_applied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidates_resume', models.FileField(blank=True, null=True, upload_to='user_resume/')),
                ('candidate_status', models.IntegerField(blank=True, null=True)),
                ('candidates_placed', models.IntegerField(blank=True, null=True)),
                ('candidates_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates_view', to='app.user_registration')),
            ],
        ),
    ]
