# Generated by Django 4.0.3 on 2022-05-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_user_registration_user_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates_applied',
            name='candidates_resume',
            field=models.FileField(blank=True, null=True, upload_to='media/user_resume/'),
        ),
    ]
