# Generated by Django 4.0.3 on 2022-05-06 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_candidates_applied_candidates_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_feedback',
            name='employer_feedback_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_feedback_view', to='app.company_registration'),
        ),
        migrations.AddField(
            model_name='user_feedback',
            name='user_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_feedback_view', to='app.user_registration'),
        ),
    ]
