# Generated by Django 4.0.3 on 2022-05-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_employer_feedback_employer_feedback_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates_applied',
            name='candidates_resume',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='company_registration',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='user_photo',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='user_resume',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
